# Path to the standard arduino tools (NOTE - there can be no spaces in the path)
ARDUINO_DIR = d:/dev/arduino-1.0.1

# Give target a logical name to suit your project
TARGET = atmel

# By default this includes all the standard libraries (You can remove the ones you dont need)
# (To add third party libraries just put the .cpp and .h file in the project directory, dont forget #include statement)
#ARDUINO_LIBS = EEPROM Ethernet Ethernet\Utility Firmata LiquidCrystal SD Servo SPI SoftwareSerial Stepper Wire Wire\Utility
ARDUINO_LIBS = 

# Name of the board your using - uno|mega2560
BOARD_TAG = uno

# Type of microcontroller - atmega328p|atmega2560
MCU = atmega328p

# Clock Speed (don't change this unless you know what your doing)
F_CPU = 16000000L

# Variant type - standard|mega
VARIANT = standard

include Arduino.mk

# Note - if it fails to compile then make sure there are no rogue spaces after any of these declarations.

